<?php
include('../include/admin_inc.php');
$objEvent=new admin;
$objBlog=new admin;
$objVenue=new admin;
$objEvent->genarateSiteMap();
$objBlog->get_all_blog();
$objVenue->get_all_venue();
$date_time=date("Y-m-dTh:m:i+00:00");
$date_created = date('Y-m-d\TH:i:s+00:00');

/*-----------FOR URL CHANGE-------------*/
$old_pattern = array("/[^a-zA-Z0-9]/", "/_+/", "/_$/");
$new_pattern = array("_", "-", "");

//$blog_en_title = strtolower(preg_replace($old_pattern, $new_pattern ,$objintro->f('page_name')));
//$blog_es_title = strtolower(preg_replace($old_pattern, $new_pattern , $objintro->f('title_sp')));


$date=date("Y-m-d h:i");
$string='<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//kpasapp.com/kpasapp.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>http://kpasapp.com/staticpage.xml</loc>
<lastmod>'.$date_created.'</lastmod>
</sitemap>
<sitemap>
<loc>http://kpasapp.com/kpasapp_about.xml</loc>
<lastmod>'.$date_created.'</lastmod>
</sitemap>
<sitemap>
<loc>http://kpasapp.com/events.xml</loc>
<lastmod>'.$date_created.'</lastmod>
</sitemap>
<sitemap>
<loc>http://kpasapp.com/blogs.xml</loc>
<lastmod>'.$date_created.'</lastmod>
</sitemap>
<sitemap>
<loc>http://kpasapp.com/venues.xml</loc>
<lastmod>'.$date_created.'</lastmod>
</sitemap>
</sitemapindex>
<!-- XML Sitemap generated by Yoast WordPress SEO -->
';


file_put_contents("../sitemap.xml", $string);


/*--------------------------kpasapp Static pages End-------------------------------------*/

$string_static='<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//kpasapp.com/kpasapp.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <url>
    <loc>http://kpasapp.com/en/home</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/home"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/inicio"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/inicio</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/home"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/inicio"/>
  </url>
  
    <url>
    <loc>http://kpasapp.com/en/about-kpasapp/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/acerca-de-kpasapp/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/"/>
  </url> 

  
    <url>
    <loc>http://kpasapp.com/en/about-baja-sur/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-baja-sur/"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-baja-california-sur/"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/acerca-de-baja-california-sur/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-baja-sur/"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-baja-california-sur/"/>
  </url> 

  
    <url>
    <loc>http://kpasapp.com/en/news/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/news/"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/news/"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/news/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/news/"/>
     <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/news/"/>
  </url>
  
      <url>
    <loc>http://kpasapp.com/en/resources/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/resources/"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/resources/"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/resources/</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/resources/"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/resources/"/>
  </url> 

</urlset>';


file_put_contents("../staticpage.xml", $string_static);

/*--------------------------kpasapp Static pages End-------------------------------------*/

/*--------------------------kpasapp about sub pages-------------------------------------*/

$string_kpasapp_about='<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//kpasapp.com/kpasapp.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <url>
    <loc>http://kpasapp.com/en/about-kpasapp/feature</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/feature"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/funciones"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/acerca-de-kpasapp/funciones</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/feature"/>
     <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/funciones"/>
  </url>
  
  <url>
    <loc>http://kpasapp.com/en/about-kpasapp/plan-pricing</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/plan-pricing"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/planes-precios"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/acerca-de-kpasapp/planes-precios</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/plan-pricing"/>
     <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/planes-precios"/>
  </url>
  
  <url>
    <loc>http://kpasapp.com/en/about-kpasapp/event_goers</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/event_goers"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/publico"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/acerca-de-kpasapp/publico</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/event_goers"/>
     <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/publico"/>
  </url>
  
  <url>
    <loc>http://kpasapp.com/en/about-kpasapp/event_professionals</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/event_professionals"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/profesionales_de_eventos"/>
  </url>
  <url>
    <loc>http://kpasapp.com/es/acerca-de-kpasapp/profesionales_de_eventos</loc>
    <xhtml:link rel="alternate" hreflang="en" href="http://kpasapp.com/en/about-kpasapp/event_professionals"/>
    <xhtml:link rel="alternate" hreflang="es" href="http://kpasapp.com/es/acerca-de-kpasapp/profesionales_de_eventos"/>
  </url>
</urlset>
';


file_put_contents("../kpasapp_about.xml", $string_kpasapp_about);

/*--------------------------kpasapp about sub pages End-------------------------------------*/

/*--------------------------kpasapp Events pages Start-------------------------------------*/

$string_events='<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="http://kpasapp.com/kpasapp.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">' . "\r\n";

    while($row = $objEvent->next_record())
    {
        //$event_name_en_url=$obj_base_path->base_path().strtolower(preg_replace($old_pattern, $new_pattern ,$objEvent->f('main_event_en')));
        //$event_name_es_url=$obj_base_path->base_path().strtolower(preg_replace($old_pattern, $new_pattern ,$objEvent->f('main_event_sp')));
        $event_name_en=strtolower(preg_replace($old_pattern, $new_pattern ,$objEvent->f('main_event_en')));
        $event_name_es=strtolower(preg_replace($old_pattern, $new_pattern ,$objEvent->f('main_event_sp')));
        $event_id=$objEvent->f('e_id');
        //echo $event_name_en_url.'<br/>';
        //echo $event_name_es_url.'<br/>';
        
        $string_events.='<url>' . "\r\n";
        $string_events.='<loc>'.$obj_base_path->base_path().'/en/event/'.$event_id."/".$event_name_en;
        $string_events.='</loc>' . "\r\n";
        $string_events.='<xhtml:link rel="alternate" hreflang="en" href="'.$obj_base_path->base_path().'/en/event/'.$event_id."/".$event_name_en.'"/>' . "\r\n";
        $string_events.='<xhtml:link rel="alternate" hreflang="es" href="'.$obj_base_path->base_path().'/es/evento/'.$event_id."/".$event_name_es.'"/>' . "\r\n";
        $string_events.='</url>' . "\r\n";
        
        $string_events.='<url>' . "\r\n";
        $string_events.='<loc>';
        $string_events.=$obj_base_path->base_path().'/es/evento/'.$event_id."/".$event_name_es;
        $string_events.='</loc>' . "\r\n";
        $string_events.='<xhtml:link rel="alternate" hreflang="en" href="'.$obj_base_path->base_path().'/en/event/'.$event_id."/".$event_name_en.'"/>' . "\r\n";
        $string_events.='<xhtml:link rel="alternate" hreflang="es" href="'.$obj_base_path->base_path().'/es/evento/'.$event_id."/".$event_name_es.'"/>' . "\r\n";
        $string_events.='</url>' . "\r\n";
        
        
    }
        $string_events.='</urlset>' . "\r\n";


file_put_contents("../events.xml", $string_events);

/*--------------------------kpasapp Events pages End-------------------------------------*/

/*--------------------------kpasapp BLOG pages Start-------------------------------------*/

$string_blog='<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//kpasapp.com/kpasapp.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'. "\r\n";
  
  
    while($row = $objBlog->next_record())
    {
    
        $blog_name_en=strtolower(preg_replace($old_pattern, $new_pattern ,$objBlog->f('page_name')));
        $blog_name_es=strtolower(preg_replace($old_pattern, $new_pattern ,$objBlog->f('title_sp')));
        $blog_id=$objBlog->f('page_id');
        //echo $event_name_en_url.'<br/>';
        //echo $event_name_es_url.'<br/>';
        
        $string_blog.='<url>' . "\r\n";
        $string_blog.='<loc>'.$obj_base_path->base_path().'/en/blog/'.$blog_id.'/'.$blog_name_en;
        $string_blog.='</loc>' . "\r\n";
        $string_blog.='<xhtml:link rel="alternate" hreflang="en" href="'.$obj_base_path->base_path().'/en/blog/'.$blog_id.'/'.$blog_name_en.'"/>' . "\r\n";
        $string_blog.='<xhtml:link rel="alternate" hreflang="es" href="'.$obj_base_path->base_path().'/es/blog/'.$blog_id.'/'.$blog_name_es.'"/>' . "\r\n";
        $string_blog.='</url>' . "\r\n";
        
        $string_blog.='<url>' . "\r\n";
        $string_blog.='<loc>';
        $string_blog.=$obj_base_path->base_path().'/es/blog/'.$blog_id.'/'.$blog_name_es;
        $string_blog.='</loc>' . "\r\n";
        $string_blog.='<xhtml:link rel="alternate" hreflang="en" href="'.$obj_base_path->base_path().'/en/blog/'.$blog_id.'/'.$blog_name_en.'"/>' . "\r\n";
        $string_blog.='<xhtml:link rel="alternate" hreflang="es" href="'.$obj_base_path->base_path().'/es/blog/'.$blog_id.'/'.$blog_name_es.'"/>' . "\r\n";
        $string_blog.='</url>' . "\r\n";
    
    
    }
    
        $string_blog.='</urlset>' . "\r\n";


file_put_contents("../blogs.xml", $string_blog);

/*--------------------------kpasapp BLOG pages END-------------------------------------*/

/*--------------------------kpasapp VENUE pages Start-------------------------------------*/

$string_venue="<?xml version='1.0' encoding='UTF-8'?><?xml-stylesheet type='text/xsl' href='//kpasapp.com/kpasapp.xsl'?>
<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9' xmlns:xhtml='http://www.w3.org/1999/xhtml'>". "\r\n";
  
  
    while($row = $objVenue->next_record())
    {
    
        $venue_name_en=strtolower(preg_replace($old_pattern, $new_pattern ,$objVenue->f('venue_name')));
        $venue_name_es=strtolower(preg_replace($old_pattern, $new_pattern ,$objVenue->f('venue_name_sp')));
        $venue_id=$objVenue->f('venue_id');
        //echo $event_name_en_url.'<br/>';
        //echo $event_name_es_url.'<br/>';
        
        $string_venue.="<url>" . "\r\n";
        $string_venue.="<loc>".$obj_base_path->base_path().'/en/venue/'.$venue_id.'/'.$venue_name_en;
        $string_venue.="</loc>" . "\r\n";
        $string_venue.="<xhtml:link rel='alternate' hreflang='en' href='".$obj_base_path->base_path()."/en/venue/".$venue_id."/".$venue_name_en."'/>" . "\r\n";
        $string_venue.="<xhtml:link rel='alternate' hreflang='es' href='".$obj_base_path->base_path()."/es/venue/".$venue_id."/".$venue_name_es."'/>" . "\r\n";
        $string_venue.="</url>" . "\r\n";
        
        $string_venue.="<url>" . "\r\n";
        $string_venue.="<loc>";
        $string_venue.=$obj_base_path->base_path().'/es/venue/'.$venue_id.'/'.$venue_name_es;
        $string_venue.="</loc>" . "\r\n";
        $string_venue.="<xhtml:link rel='alternate' hreflang='en' href='".$obj_base_path->base_path()."/en/venue/".$venue_id."/".$venue_name_en."'/>" . "\r\n";
        $string_venue.="<xhtml:link rel='alternate' hreflang='es' href='".$obj_base_path->base_path()."/es/venue/".$venue_id."/".$venue_name_es."'/>" . "\r\n";
        $string_venue.="</url>" . "\r\n";
    
    
    }
    
        $string_venue.="</urlset>" . "\r\n";


file_put_contents("../venues.xml", $string_venue);

/*--------------------------kpasapp VENUE pages END-------------------------------------*/
//echo "hello= ".$_REQUEST;
//if($_REQUEST['from']='blog_create')
//   {
//     echo $obj_base_path->base_path()."/admin/list_page.php?err=3";
//   }
//elseif($_REQUEST['from']='blog_edit')
//    {
//     echo $obj_base_path->base_path()."/admin/list_page.php?err=2";  
//    }
//else($_REQUEST['from']='')
//{
    echo "<a href='http://kpasapp.com/sitemap.xml'>click on this link to view the sitemap</a><br/>";
    echo "<a href='http://kpasapp.com/admin/event-list'>Get back to admin</a>";
//}
?>